# Generated by Django 4.0.4 on 2024-05-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_facultad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('abrebiación', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_programa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('abrebiación', models.CharField(max_length=10)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.facultade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_punto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_punto', models.CharField(max_length=50)),
                ('id_estacion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('código', models.CharField(max_length=11)),
                ('identificación', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('id_programas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.programa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parkine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_parking', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('id_punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.punto')),
                ('id_usurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
